name: chronly

services:
  chronly:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chronly
    hostname: chronly
    ports:
      - "5600:5600"
    volumes:
      - aw-data:/data
    restart: unless-stopped

volumes:
  aw-data:
    name: chronly_aw-data
    external: true
